apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: prod
    app: ic-webapp
  name: ic-webapp
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: ic-webapp

  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - image: nzapa/ic-webapp-3:1.0
        name: ic-webapp
        env:
        - name: ODOO_URL
          value: http://54.147.46.197:30069/
        - name: PGADMIN_URL
          value: http://54.147.46.197:30050/
        ports:
        - containerPort: 8080
          name: ic-webapp
